import jwt from "jsonwebtoken";
import { JWT_SECRET } from "../constants/env";

/**
 * Decodes a jwt generated token down to the employee it was
 * generated from
 *
 * @param {string} token A token generated by jwt
 * @returns {string} The employee number the jwt was generated from
 */
const decodeToken = (token) => jwt.verify(token, JWT_SECRET);

export default decodeToken;
